### ISSUE TITLE
dev: replacing agent dep to local path make it not able to install by `go install`

### ISSUE THREAD

**Issue by zwpaper** [tensorchord/openmodelz#133]
mdz replace agent to parent dir `../agent`, this is convenient for local develop, but make it not able to install by `go install`.

how about using the full URL when upload intree, and create a `make local-build` to change it locally.

https://github.com/tensorchord/openmodelz/blob/c23067f0818305c675be06950c883faa3299e386/mdz/go.mod#L5

https://github.com/tensorchord/openmodelz/blob/main/agent/go.mod#L7-L8

**Comment by cybergeekgyan** [comment]
can you assign It to me and help me proceed with this issue to resolve it ... @zwpaper

**Comment by gaocegege** [comment]
SGTM, I think this works.

**Comment by gaocegege** [comment]
@zwpaper Could you please help with this issue?

**Comment by zwpaper** [comment]
of cause, how about we do it this way: @gaocegege 

1. add a Make command, `build-local`, it check the local deps in `go.mod`, build directly if local deps existed; comment out the 3 deps, add local deps then build if no local deps found.
2. `make build` should make sure there are no local deps, and then build.
3. add docs for `local-build` and `build`
4. add docs for `go install`

@cybergeekgyan feel free to start implement after we on the same page with @gaocegege

**Comment by gaocegege** [comment]
@cybergeekgyan Already picked 2 issus up. Could you please help with this issue? @zwpaper 

Yeah I think we are on the same page.

**Comment by zwpaper** [comment]
ok, I will fire a PR later today

**Comment by gaocegege** [comment]
Could we close this? @zwpaper
