### ISSUE TITLE
[bug] website index.html style error

### ISSUE THREAD

**Issue by lxd5866** [tensorchord/openmodelz#193]
- how to reappear
 click this logo
<img width="1730" alt="image" src="https://github.com/tensorchord/openmodelz/assets/10388914/8da32e34-5c14-4d0f-990f-6b9f717b6351">

you will see
<img width="1153" alt="image" src="https://github.com/tensorchord/openmodelz/assets/10388914/fb4afd03-c0c0-4121-bb7c-fabfbabc28d8">

**Comment by kemingy** [comment]
Thanks for your feedback. Will fix this ASAP.
